import turtle
turtle.reset()
point = (0,0)
turtle.circle(20)
turtle.penup()
point = (50,-30)
turtle.goto(point)
turtle.left(90)
turtle.pendown()
turtle.forward(90)
turtle.penup()
point = (80,60)
print   (point)
turtle.goto(point)
turtle.pendown()
turtle.right(90)
turtle.forward(60)
point = (110,60)
turtle.goto(point)
turtle.right(90)
turtle.forward(30)
point = turtle.position()
turtle.right(15)
turtle.forward(60)
turtle.goto(point)
turtle.left(30)
turtle.forward(60)
point = (170,60)
turtle.penup()
turtle.goto(point)
turtle.pendown( )
turtle.right(15)
turtle.forward(90)
point = (200,60)
turtle.penup()
turtle.goto (point)
turtle.left(90)
turtle.pendown()
turtle.forward(30)
turtle.penup()
point = (180, 40)
turtle.goto (point)
turtle.pendown( )
turtle.forward(70)
turtle.penup()
point = (215,-15)
turtle.goto(point)
turtle.pendown()
turtle.circle(15)
turtle.penup()
point = (270,60)
turtle.goto(point)
turtle.right(90)
turtle.pendown()
turtle.forward(90)
point = (270,10)
turtle.goto(point)
turtle.right(90)
turtle.forward(30)
turtle.penup()
point = (270,-10)
turtle.goto(point)
turtle.pendown()
turtle.forward(30)
turtle.penup()
point = (270,-30)
turtle.goto(point)
turtle.pendown()
turtle.circle(15)
